from sqlalchemy.orm import Session
from postgre import SessionLocal
from models import Livro, Base
from postgre import engine
from datetime import datetime, UTC


# Cria as tabelas se não existirem
Base.metadata.create_all(bind=engine)

def inserir_livros_iniciais():
    db: Session = SessionLocal()

    livros = [
       Livro(nome='O Senhor dos Anéis', autor='J.R.R. Tolkien', descricao='A Sociedade do Anel', genero='Fantasia', capa=''),
       Livro(nome='Harry Potter', autor='J.K. Rowling', descricao='A Pedra Filosofal', genero='Fantasia', capa=''),
       Livro(nome='Hábitos Atômicos', autor='James Clear', descricao='Guia prático para criar bons hábitos', genero='Desenvolvimento pessoal', capa=''),
       Livro(nome='1984', autor='George Orwell', descricao='Sociedade distópica sob vigilância', genero='Distopia', capa=''),
       Livro(nome='Dom Quixote', autor='Miguel de Cervantes', descricao='Cavaleiro em busca de justiça', genero='Clássico / Romance', capa=''),
       Livro(nome='O Pequeno Príncipe', autor='Antoine de Saint-Exupéry', descricao='Viagem filosófica e poética', genero='Fábula / Filosófico', capa=''),
       Livro(nome='A Revolução dos Bichos', autor='George Orwell', descricao='Sátira política com animais', genero='Sátira / Distopia', capa=''),
       Livro(nome='O Código Da Vinci', autor='Dan Brown', descricao='Suspense envolvendo religião e arte', genero='Suspense / Mistério', capa=''),
       Livro(nome='Moby Dick', autor='Herman Melville', descricao='A caça à baleia branca', genero='Aventura / Clássico', capa=''),
       Livro(nome='Crime e Castigo', autor='Fiódor Dostoiévski', descricao='Drama psicológico e culpa', genero='Drama psicológico / Clássico', capa=''),
       Livro(nome='O Alquimista', autor='Paulo Coelho', descricao='Jornada espiritual por um tesouro', genero='Ficção filosófica', capa=''),
       Livro(nome='A Guerra dos Tronos', autor='George R.R. Martin', descricao='Intrigas em Westeros', genero='Fantasia épica', capa=''),
       Livro(nome='O Morro dos Ventos Uivantes', autor='Emily Brontë', descricao='Romance gótico e vingança', genero='Romance gótico', capa=''),
       Livro(nome='Cem Anos de Solidão', autor='Gabriel García Márquez', descricao='Saga da família Buendía', genero='Realismo mágico', capa=''),
       Livro(nome='A Lâmina da Assassina', autor='Sarah J. Maas', descricao='Prelúdio da saga Trono de Vidro', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Trono de Vidro', autor='Sarah J. Maas', descricao='Assassina em competição mortal', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Coroa da Meia-Noite', autor='Sarah J. Maas', descricao='Segredos e traições', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Herdeira do Fogo', autor='Sarah J. Maas', descricao='Poderes despertando', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Rainha das Sombras', autor='Sarah J. Maas', descricao='Confronto com o passado', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Império de Tempestades', autor='Sarah J. Maas', descricao='Aliados improváveis', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Torre do Alvorecer', autor='Sarah J. Maas', descricao='Aventuras em novo continente', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Reino das Cinzas', autor='Sarah J. Maas', descricao='Conclusão épica', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Corte de Espinhos e Rosas', autor='Sarah J. Maas', descricao='Bela e a Fera reimaginado', genero='Fantasia / Romance / Jovem adulto', capa=''),
       Livro(nome='Corte de Névoa e Fúria', autor='Sarah J. Maas', descricao='Segredos do mundo feérico', genero='Fantasia / Romance / Jovem adulto', capa=''),
       Livro(nome='Corte de Asas e Ruína', autor='Sarah J. Maas', descricao='Batalha entre reinos', genero='Fantasia / Romance / Jovem adulto', capa=''),
       Livro(nome='Corte de Gelo e Estrelas', autor='Sarah J. Maas', descricao='História pós-guerra', genero='Fantasia / Romance / Jovem adulto', capa=''),
       Livro(nome='Corte de Chamas Prateadas', autor='Sarah J. Maas', descricao='Nova protagonista em ascensão', genero='Fantasia / Romance / New adult', capa=''),
       Livro(nome='Casa de Terra e Sangue', autor='Sarah J. Maas', descricao='Mundo urbano com magia', genero='Fantasia / New adult', capa=''),
       Livro(nome='Casa de Céu e Sopro', autor='Sarah J. Maas', descricao='Conflitos e revelações', genero='Fantasia / New adult', capa=''),
       Livro(nome='Casa de Chama e Sombra', autor='Sarah J. Maas', descricao='Último capítulo da saga', genero='Fantasia / New adult', capa=''),
       Livro(nome='Orgulho e Preconceito', autor='Jane Austen', descricao='Romance clássico sobre amor e sociedade', genero='Romance / Clássico', capa=''),
       Livro(nome='O Grande Gatsby', autor='F. Scott Fitzgerald', descricao='Crítica social e o sonho americano', genero='Clássico / Romance', capa=''),
       Livro(nome='As Crônicas de Nárnia: O Leão, a Feiticeira e o Guarda-Roupa', autor='C.S. Lewis', descricao='Aventuras em um mundo mágico', genero='Fantasia / Infantil', capa=''),
       Livro(nome='A Menina que Roubava Livros', autor='Markus Zusak', descricao='História emocionante ambientada na Segunda Guerra Mundial', genero='Drama Histórico', capa=''),
       Livro(nome='Percy Jackson e o Ladrão de Raios', autor='Rick Riordan', descricao='Um jovem descobre ser filho de um deus grego', genero='Fantasia / Mitologia / Jovem adulto', capa=''),
       Livro(nome='O Diário de Anne Frank', autor='Anne Frank', descricao='Relato da vida de uma adolescente durante o Holocausto', genero='Biografia / História', capa=''),
       Livro(nome='Ensaio sobre a Cegueira', autor='José Saramago', descricao='Uma epidemia de cegueira branca atinge uma cidade', genero='Distopia / Ficção Filosófica', capa=''),
       Livro(nome='O Conto da Aia', autor='Margaret Atwood', descricao='Sociedade totalitária onde mulheres são propriedade', genero='Distopia / Ficção Científica', capa=''),
       Livro(nome='Extraordinário', autor='R.J. Palacio', descricao='A vida de um menino com deformidade facial', genero='Drama / Jovem adulto', capa=''),
       Livro(nome='Sapiens: Uma Breve História da Humanidade', autor='Yuval Noah Harari', descricao='Exploração da história da humanidade', genero='Não Ficção / História', capa=''),
       Livro(nome='Mulheres que Correm com os Lobos', autor='Clarissa Pinkola Estés', descricao='Mitos e histórias sobre o poder feminino', genero='Psicologia / Feminismo', capa=''),
       Livro(nome='Mindset: A Nova Psicologia do Sucesso', autor='Carol S. Dweck', descricao='A importância da mentalidade no sucesso', genero='Desenvolvimento Pessoal / Psicologia', capa=''),
       Livro(nome='O Poder do Hábito', autor='Charles Duhigg', descricao='Como os hábitos funcionam e como podemos mudá-los', genero='Não Ficção / Psicologia', capa=''),
       Livro(nome='A Culpa é das Estrelas', autor='John Green', descricao='Romance adolescente sobre amor e doença', genero='Romance / Jovem adulto', capa=''),
       Livro(nome='Uma Breve História do Tempo', autor='Stephen Hawking', descricao='Explicação de conceitos cosmológicos para leigos', genero='Não Ficção / Ciência', capa=''),
       Livro(nome='O Silmarillion', autor='J.R.R. Tolkien', descricao='História da criação e mitologia da Terra-média', genero='Fantasia / Mitologia', capa=''),
       Livro(nome='O Hobbit', autor='J.R.R. Tolkien', descricao='Aventura de Bilbo Bolseiro em busca de um tesouro', genero='Fantasia / Aventura', capa=''),
       Livro(nome='O nome do Vento', autor='Patrick Rothfuss', descricao='A história de Kvothe, um jovem prodígio', genero='Fantasia / Aventura', capa=''),
       Livro(nome='A Bússola de Ouro', autor='Philip Pullman', descricao='Aventuras em um mundo paralelo', genero='Fantasia / Aventura', capa=''),
       Livro(nome='O Senhor dos Anéis: As Duas Torres', autor='J.R.R. Tolkien', descricao='Continuação da jornada da Sociedade do Anel', genero='Fantasia / Aventura', capa=''),
       Livro(nome='O Senhor dos Anéis: O Retorno do Rei', autor='J.R.R. Tolkien', descricao='Conclusão épica da saga do Anel', genero='Fantasia / Aventura', capa=''),
       Livro(nome='A Rainha Vermelha', autor='Victoria Aveyard', descricao='Um mundo dividido entre sangue vermelho e prateado', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='A Seleção', autor='Kiera Cass', descricao='Uma competição para se tornar a futura rainha', genero='Romance / Jovem adulto', capa=''),
       Livro(nome='A Esperança', autor='Suzanne Collins', descricao='O desfecho da trilogia Jogos Vorazes', genero='Distopia / Ficção Científica', capa=''),
       Livro(nome='Jogos Vorazes', autor='Suzanne Collins', descricao='Uma competição mortal em um futuro distópico', genero='Distopia / Ficção Científica', capa=''),
       Livro(nome='Em Chamas', autor='Suzanne Collins', descricao='Continuação da luta de Katniss Everdeen', genero='Distopia / Ficção Científica', capa=''),
       Livro(nome='O Ódio que Você Semeia', autor='Angie Thomas', descricao='A luta contra o racismo e a brutalidade policial', genero='Drama / Jovem adulto', capa=''),
       Livro(nome='O Sol é Para Todos', autor='Harper Lee', descricao='Justiça e racismo no sul dos Estados Unidos', genero='Clássico / Drama', capa=''),
       Livro(nome='O Hobbit: Uma Jornada Inesperada', autor='J.R.R. Tolkien', descricao='A primeira parte da aventura do Hobbit', genero='Fantasia / Aventura', capa=''),
       Livro(nome='O Hobbit: A Desolação de Smaug', autor='J.R.R. Tolkien', descricao='Continuação da jornada em direção ao dragão', genero='Fantasia / Aventura', capa=''),
       Livro(nome='O Hobbit: A Batalha dos Cinco Exércitos', autor='J.R.R. Tolkien', descricao='Conclusão da jornada do Hobbit', genero='Fantasia / Aventura', capa=''),
       Livro(nome='Percy Jackson e o Mar de Monstros', autor='Rick Riordan', descricao='Continuação da saga de Percy', genero='Fantasia / Mitologia / Jovem adulto', capa=''),
       Livro(nome='Percy Jackson e a Maldição do Titã', autor='Rick Riordan', descricao='Mais desafios para Percy e seus amigos', genero='Fantasia / Mitologia / Jovem adulto', capa=''),
       Livro(nome='Percy Jackson e o Desafio dos Heróis', autor='Rick Riordan', descricao='Batalha final contra forças do mal', genero='Fantasia / Mitologia / Jovem adulto', capa=''),
       Livro(nome='Harry Potter e a Câmara Secreta', autor='J.K. Rowling', descricao='Segunda aventura de Harry em Hogwarts', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Harry Potter e o Prisioneiro de Azkaban', autor='J.K. Rowling', descricao='Descobertas sobre o passado de Harry', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Harry Potter e o Cálice de Fogo', autor='J.K. Rowling', descricao='Competição perigosa no Torneio Tribruxo', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Harry Potter e a Ordem da Fênix', autor='J.K. Rowling', descricao='Luta contra as forças das trevas', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Harry Potter e o Enigma do Príncipe', autor='J.K. Rowling', descricao='Segredos do passado de Voldemort', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Harry Potter e as Relíquias da Morte', autor='J.K. Rowling', descricao='Batalha final contra Voldemort', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='A Menina do Vale', autor='Bel Pesce', descricao='História de empreendedorismo e sucesso', genero='Biografia / Desenvolvimento pessoal', capa=''),
       Livro(nome='O Poder do Agora', autor='Eckhart Tolle', descricao='Prática da atenção plena e presença', genero='Desenvolvimento pessoal / Espiritualidade', capa=''),
       Livro(nome='Pai Rico, Pai Pobre', autor='Robert T. Kiyosaki', descricao='Educação financeira para o sucesso', genero='Finanças pessoais', capa=''),
       Livro(nome='Como Fazer Amigos e Influenciar Pessoas', autor='Dale Carnegie', descricao='Técnicas para melhorar relacionamentos', genero='Autoajuda', capa=''),
       Livro(nome='Os Segredos da Mente Milionária', autor='T. Harv Eker', descricao='Mentalidade para a riqueza', genero='Finanças pessoais / Desenvolvimento pessoal', capa=''),
       Livro(nome='A Arte da Guerra', autor='Sun Tzu', descricao='Estratégias militares e de vida', genero='Estratégia / Filosofia', capa=''),
       Livro(nome='O Segredo', autor='Rhonda Byrne', descricao='Lei da atração e pensamento positivo', genero='Autoajuda / Espiritualidade', capa=''),
       Livro(nome='O Diário de um Mago', autor='Paulo Coelho', descricao='Jornada de autodescoberta', genero='Ficção filosófica / Espiritualidade', capa=''),
       Livro(nome='O Lobo de Wall Street', autor='Jordan Belfort', descricao='História real de um corretor de ações', genero='Biografia / Negócios', capa=''),
       Livro(nome='A Revolta de Atlas', autor='Ayn Rand', descricao='Filosofia objetivista em romance', genero='Ficção filosófica', capa=''),
       Livro(nome='O Caçador de Pipas', autor='Khaled Hosseini', descricao='Amizade e redenção no Afeganistão', genero='Drama / Romance', capa=''),
       Livro(nome='Jogador Número 1', autor='Ernest Cline', descricao='Realidade virtual e cultura pop', genero='Ficção Científica', capa=''),
       Livro(nome='O Velho e o Mar', autor='Ernest Hemingway', descricao='Luta entre hnomem e natureza', genero='Clássico / Aventura', capa=''),
       Livro(nome='O Menino do Pijama Listrado', autor='John Boyne', descricao='Amizade durante o Holocausto', genero='Drama / História', capa=''),
       Livro(nome='A Cabana', autor='William P. Young', descricao='História de fé e perdão', genero='Ficção / Espiritualidade', capa=''),
       Livro(nome='O Menino do Dedo Verde', autor='Maurice Druon', descricao='História mágica e poética', genero='Infantil / Fantasia', capa=''),
       Livro(nome='O Vendedor de Sonhos', autor='Augusto Cury', descricao='Reflexão sobre a vida e felicidade', genero='Autoajuda / Ficção', capa=''),
       Livro(nome='O Corpo Fala', autor='Pierre Weil', descricao='Comunicação não-verbal', genero='Psicologia', capa=''),
       Livro(nome='O Poder do Subconsciente', autor='Joseph Murphy', descricao='Influência do subconsciente na vida', genero='Autoajuda / Psicologia', capa=''),
       Livro(nome='O Príncipe', autor='Nicolau Maquiavel', descricao='Tratado sobre poder e política', genero='Filosofia / Política', capa=''),
       Livro(nome='A Arte da Felicidade', autor='Dalai Lama', descricao='Ensinamentos sobre felicidade', genero='Espiritualidade / Psicologia', capa=''),
       Livro(nome='O Hnomem Mais Rico da Babilônia', autor='George S. Clason', descricao='Princípios de finanças pessoais', genero='Finanças pessoais', capa=''),
       Livro(nome='O Poder da Ação', autor='Paulo Vieira', descricao='Transformação pessoal', genero='Desenvolvimento pessoal', capa=''),
       Livro(nome='Quem Pensa, Enriquece', autor='Napoleon Hill', descricao='Segredos da mente milionária', genero='Autoajuda / Finanças', capa=''),
       Livro(nome='A Sutil Arte de Ligar o F*da-se', autor='Mark Manson', descricao='Abordagem realista para a felicidade', genero='Autoajuda', capa=''),
       Livro(nome='Como Fazer Amigos e Influenciar Pessoas no Século 21', autor='Dale Carnegie', descricao='Versão atualizada de clássicos', genero='Autoajuda', capa=''),
       Livro(nome='O Menino do Pijama Listrado', autor='John Boyne', descricao='Drama da Segunda Guerra Mundial', genero='Drama / História', capa=''),
       Livro(nome='O Caçador de Pipas', autor='Khaled Hosseini', descricao='História de amizade e perdão', genero='Drama / Romance', capa=''),
       Livro(nome='Sapiens', autor='Yuval Noah Harari', descricao='História da humanidade', genero='Não Ficção / História', capa=''),
       Livro(nome='Homo Deus', autor='Yuval Noah Harari', descricao='Futuro da humanidade', genero='Não Ficção / Futurismo', capa=''),
       Livro(nome='21 Lições para o Século 21', autor='Yuval Noah Harari', descricao='Desafios contemporâneos', genero='Não Ficção / Atualidades', capa=''),
       Livro(nome='O Conto da Aia', autor='Margaret Atwood', descricao='Distopia feminista', genero='Ficção Científica / Distopia', capa=''),
       Livro(nome='A Revolução dos Bichos', autor='George Orwell', descricao='Sátira política', genero='Distopia / Ficção', capa=''),
       Livro(nome='1984', autor='George Orwell', descricao='Distopia totalitária', genero='Distopia / Ficção', capa=''),
       Livro(nome='Fahrenheit 451', autor='Ray Bradbury', descricao='Sociedade que queima livros', genero='Ficção Científica / Distopia', capa=''),
       Livro(nome='Admirável Mundo Novo', autor='Aldous Huxley', descricao='Distopia tecnológica', genero='Ficção Científica / Distopia', capa=''),
       Livro(nome='Laranja Mecânica', autor='Anthony Burgess', descricao='Violência e controle social', genero='Distopia / Ficção', capa=''),
       Livro(nome='O Senhor das Moscas', autor='William Golding', descricao='Sobrevivência e natureza humana', genero='Drama / Ficção', capa=''),
       Livro(nome='O Processo', autor='Franz Kafka', descricao='Absurdo e burocracia', genero='Ficção / Filosofia', capa=''),
       Livro(nome='Metamorfose', autor='Franz Kafka', descricao='Transformação e alienação', genero='Ficção / Filosofia', capa=''),
       Livro(nome='O Estrangeiro', autor='Albert Camus', descricao='Existencialismo e absurdo', genero='Ficção / Filosofia', capa=''),
       Livro(nome='A Náusea', autor='Jean-Paul Sartre', descricao='Existencialismo', genero='Ficção / Filosofia', capa=''),
       Livro(nome='O Pequeno Príncipe', autor='Antoine de Saint-Exupéry', descricao='Fábula filosófica', genero='Fábula / Filosofia', capa=''),
       Livro(nome='O Hnomem Invisível', autor='Ralph Ellison', descricao='Identidade e racismo', genero='Ficção / Drama', capa=''),
       Livro(nome='O Sol é Para Todos', autor='Harper Lee', descricao='Justiça e racismo', genero='Clássico / Drama', capa=''),
       Livro(nome='A Cor Púrpura', autor='Alice Walker', descricao='Vida de mulheres afro-americanas', genero='Drama / Ficção', capa=''),
       Livro(nome='Cem Anos de Solidão', autor='Gabriel García Márquez', descricao='Realismo mágico', genero='Ficção / Realismo mágico', capa=''),
       Livro(nome='O Amor nos Tempos do Cólera', autor='Gabriel García Márquez', descricao='História de amor duradoura', genero='Romance / Ficção', capa=''),
       Livro(nome='Memórias Póstumas de Brás Cubas', autor='Machado de Assis', descricao='Narrativa inovadora', genero='Clássico / Literatura Brasileira', capa=''),
       Livro(nome='Dom Casmurro', autor='Machado de Assis', descricao='Narrador não confiável', genero='Clássico / Literatura Brasileira', capa=''),
       Livro(nome='Vidas Secas', autor='Graciliano Ramos', descricao='Vida no sertão nordestino', genero='Clássico / Literatura Brasileira', capa=''),
       Livro(nome='Grande Sertão: Veredas', autor='Guimarães Rosa', descricao='Narrativa complexa', genero='Clássico / Literatura Brasileira', capa=''),
       Livro(nome='Capitães da Areia', autor='Jorge Amado', descricao='Meninos de rua em Salvador', genero='Clássico / Literatura Brasileira', capa=''),
       Livro(nome='O Guarani', autor='José de Alencar', descricao='Romance indianista', genero='Clássico / Literatura Brasileira', capa=''),
       Livro(nome='Iracema', autor='José de Alencar', descricao='Romance indianista', genero='Clássico / Literatura Brasileira', capa=''),
       Livro(nome='Senhora', autor='José de Alencar', descricao='Romance urbano', genero='Clássico / Literatura Brasileira', capa=''),
       Livro(nome='A Moreninha', autor='Joaquim Manuel de Macedo', descricao='Romance romântico', genero='Clássico / Literatura Brasileira', capa=''),
       Livro(nome='O Primo Basílio', autor='José Maria de Eça de Queirós', descricao='Romance realista', genero='Clássico / Literatura Portuguesa', capa=''),
       Livro(nome='Os Maias', autor='José Maria de Eça de Queirós', descricao='Crítica social', genero='Clássico / Literatura Portuguesa', capa=''),
       Livro(nome='Ensaio sobre a Cegueira', autor='José Saramago', descricao='Distopia', genero='Ficção / Distopia', capa=''),
       Livro(nome='O Evangelho Segundo Jesus Cristo', autor='José Saramago', descricao='Narrativa polêmica', genero='Ficção / Religião', capa=''),
       Livro(nome='Blindness', autor='José Saramago', descricao='Ensaio sobre a cegueira', genero='Ficção / Distopia', capa=''),
       Livro(nome='O Alquimista', autor='Paulo Coelho', descricao='Jornada espiritual', genero='Ficção / Espiritualidade', capa=''),
       Livro(nome='Brida', autor='Paulo Coelho', descricao='História de uma jovem bruxa', genero='Ficção / Espiritualidade', capa=''),
       Livro(nome='Onze Minutos', autor='Paulo Coelho', descricao='Exploração do amor e sexualidade', genero='Ficção / Romance', capa=''),
       Livro(nome='Veronika Decide Morrer', autor='Paulo Coelho', descricao='Reflexão sobre vida e morte', genero='Ficção / Romance', capa=''),
       Livro(nome='O Demônio e a Srta. Prym', autor='Paulo Coelho', descricao='Batalha entre o bem e o mal', genero='Ficção / Romance', capa=''),
       Livro(nome='O Monte Cinco', autor='Paulo Coelho', descricao='Romance espiritual', genero='Ficção / Espiritualidade', capa=''),
       Livro(nome='Onze Minutos', autor='Paulo Coelho', descricao='Exploração do amor e sexualidade', genero='Ficção / Romance', capa=''),
       Livro(nome='Sete Minutos Depois da Meia-Noite', autor='Patrick Ness', descricao='História de fantasia e drama', genero='Fantasia / Drama', capa=''),
       Livro(nome='A Menina que Roubava Livros', autor='Markus Zusak', descricao='História emocionante', genero='Drama / Histórico', capa=''),
       Livro(nome='O Caçador de Pipas', autor='Khaled Hosseini', descricao='Amizade e redenção', genero='Drama / Romance', capa=''),
       Livro(nome='A Culpa é das Estrelas', autor='John Green', descricao='Romance adolescente', genero='Romance / Jovem adulto', capa=''),
       Livro(nome='O Diário de Anne Frank', autor='Anne Frank', descricao='Relato do Holocausto', genero='Biografia / História', capa=''),
       Livro(nome='Extraordinário', autor='R.J. Palacio', descricao='Vida com deformidade facial', genero='Drama / Jovem adulto', capa=''),
       Livro(nome='O Código Da Vinci', autor='Dan Brown', descricao='Mistério religioso', genero='Suspense / Mistério', capa=''),
       Livro(nome='Anjos e Demônios', autor='Dan Brown', descricao='Mistério e suspense', genero='Suspense / Mistério', capa=''),
       Livro(nome='O Símbolo Perdido', autor='Dan Brown', descricao='Mais mistérios e códigos', genero='Suspense / Mistério', capa=''),
       Livro(nome='Inferno', autor='Dan Brown', descricao='Thriller com referências culturais', genero='Suspense / Mistério', capa=''),
       Livro(nome='Origem', autor='Dan Brown', descricao='Mistério e ciência', genero='Suspense / Mistério', capa=''),
       Livro(nome='A Garota no Trem', autor='Paula Hawkins', descricao='Suspense psicológico', genero='Suspense / Thriller', capa=''),
       Livro(nome='Garota Exemplar', autor='Gillian Flynn', descricao='Mistério e thriller', genero='Suspense / Thriller', capa=''),
       Livro(nome='O Silêncio dos Inocentes', autor='Thomas Harris', descricao='Thriller psicológico', genero='Suspense / Thriller', capa=''),
       Livro(nome='O Código Da Vinci', autor='Dan Brown', descricao='Suspense religioso', genero='Suspense / Mistério', capa=''),
       Livro(nome='O Caçador de Pipas', autor='Khaled Hosseini', descricao='História comovente', genero='Drama / Romance', capa=''),
       Livro(nome='O Hobbit', autor='J.R.R. Tolkien', descricao='Aventuras do Hobbit', genero='Fantasia / Aventura', capa=''),
       Livro(nome='Harry Potter e a Pedra Filosofal', autor='J.K. Rowling', descricao='Primeira aventura de Harry Potter', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='O Senhor dos Anéis', autor='J.R.R. Tolkien', descricao='Saga épica da Terra-média', genero='Fantasia / Aventura', capa=''),
       Livro(nome='O Apanhador no Campo de Centeio', autor='J.D. Salinger', descricao='Adolescência e alienação', genero='Clássico / Ficção', capa=''),
       Livro(nome='O Código Da Vinci', autor='Dan Brown', descricao='Mistério religioso', genero='Suspense / Mistério', capa=''),
       Livro(nome='A Guerra dos Tronos', autor='George R.R. Martin', descricao='Luta pelo trono', genero='Fantasia épica', capa=''),
       Livro(nome='O Silmarillion', autor='J.R.R. Tolkien', descricao='História da Terra-média', genero='Fantasia / Mitologia', capa=''),
       Livro(nome='A Culpa é das Estrelas', autor='John Green', descricao='Romance e doença', genero='Romance / Jovem adulto', capa=''),
       Livro(nome='O Menino do Pijama Listrado', autor='John Boyne', descricao='Amizade durante a guerra', genero='Drama / História', capa=''),
       Livro(nome='O nome do Vento', autor='Patrick Rothfuss', descricao='História do herói Kvothe', genero='Fantasia / Aventura', capa=''),
       Livro(nome='O Hobbit: Uma Jornada Inesperada', autor='J.R.R. Tolkien', descricao='Primeira parte do Hobbit', genero='Fantasia / Aventura', capa=''),
       Livro(nome='O Hobbit: A Desolação de Smaug', autor='J.R.R. Tolkien', descricao='Continuação da aventura', genero='Fantasia / Aventura', capa=''),
       Livro(nome='O Hobbit: A Batalha dos Cinco Exércitos', autor='J.R.R. Tolkien', descricao='Conclusão da saga', genero='Fantasia / Aventura', capa=''),
       Livro(nome='Jogos Vorazes', autor='Suzanne Collins', descricao='Competição mortal', genero='Distopia / Ficção Científica', capa=''),
       Livro(nome='Em Chamas', autor='Suzanne Collins', descricao='Continuação da saga', genero='Distopia / Ficção Científica', capa=''),
       Livro(nome='A Esperança', autor='Suzanne Collins', descricao='Desfecho da trilogia', genero='Distopia / Ficção Científica', capa=''),
       Livro(nome='Percy Jackson e o Ladrão de Raios', autor='Rick Riordan', descricao='Mitologia grega e aventura', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Percy Jackson e o Mar de Monstros', autor='Rick Riordan', descricao='Segunda aventura', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Percy Jackson e a Maldição do Titã', autor='Rick Riordan', descricao='Terceira aventura', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='Percy Jackson e o Último Olimpiano', autor='Rick Riordan', descricao='Conclusão da saga', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='O Código Da Vinci', autor='Dan Brown', descricao='Mistério e suspense', genero='Suspense / Mistério', capa=''),
       Livro(nome='Anjos e Demônios', autor='Dan Brown', descricao='Thriller religioso', genero='Suspense / Mistério', capa=''),
       Livro(nome='O Símbolo Perdido', autor='Dan Brown', descricao='Mais mistérios', genero='Suspense / Mistério', capa=''),
       Livro(nome='Inferno', autor='Dan Brown', descricao='Thriller e simbologia', genero='Suspense / Mistério', capa=''),
       Livro(nome='Origem', autor='Dan Brown', descricao='Mistério e ciência', genero='Suspense / Mistério', capa=''),
       Livro(nome='O Diário de Anne Frank', autor='Anne Frank', descricao='Relato do Holocausto', genero='Biografia / História', capa=''),
       Livro(nome='Extraordinário', autor='R.J. Palacio', descricao='Vida com deformidade facial', genero='Drama / Jovem adulto', capa=''),
       Livro(nome='O Menino do Pijama Listrado', autor='John Boyne', descricao='Amizade na guerra', genero='Drama / História', capa=''),
       Livro(nome='O Caçador de Pipas', autor='Khaled Hosseini', descricao='Amizade e redenção', genero='Drama / Romance', capa=''),
       Livro(nome='A Culpa é das Estrelas', autor='John Green', descricao='Romance jovem adulto', genero='Romance / Jovem adulto', capa=''),
       Livro(nome='A Menina que Roubava Livros', autor='Markus Zusak', descricao='História da Segunda Guerra', genero='Drama / História', capa=''),
       Livro(nome='O Hobbit', autor='J.R.R. Tolkien', descricao='Aventura do Hobbit', genero='Fantasia / Aventura', capa=''),
       Livro(nome='O Senhor dos Anéis', autor='J.R.R. Tolkien', descricao='Saga da Terra-média', genero='Fantasia / Aventura', capa=''),
       Livro(nome='Harry Potter e a Pedra Filosofal', autor='J.K. Rowling', descricao='Primeira aventura', genero='Fantasia / Jovem adulto', capa=''),
       Livro(nome='O Apanhador no Campo de Centeio', autor='J.D. Salinger', descricao='Adolescência e alienação', genero='Clássico / Ficção', capa=''),
       Livro(nome='O Código Da Vinci', autor='Dan Brown', descricao='Mistério religioso', genero='Suspense / Mistério', capa=''),
       Livro(nome='A Guerra dos Tronos', autor='George R.R. Martin', descricao='Luta pelo trono', genero='Fantasia épica', capa=''),
       Livro(nome='O Silmarillion', autor='J.R.R. Tolkien', descricao='História da Terra-média', genero='Fantasia / Mitologia', capa=''),
       Livro(nome='A Culpa é das Estrelas', autor='John Green', descricao='Romance e doença', genero='Romance / Jovem adulto', capa=''),
       Livro(nome='O Menino do Pijama Listrado', autor='John Boyne', descricao='Amizade durante a guerra', genero='Drama / História', capa=''),
       Livro(nome='O nome do Vento', autor='Patrick Rothfuss', descricao='História do herói Kvothe', genero='Fantasia / Aventura', capa=''),
       Livro(nome='O Hobbit: Uma Jornada Inesperada', autor='J.R.R. Tolkien', descricao='Primeira parte do Hobbit', genero='Fantasia / Aventura', capa=''),
       Livro(nome='O Hobbit: A Desolação de Smaug', autor='J.R.R. Tolkien', descricao='Continuação da aventura', genero='Fantasia / Aventura', capa=''),
       Livro(nome='O Hobbit: A Batalha dos Cinco Exércitos', autor='J.R.R. Tolkien', descricao='Conclusão da saga', genero='Fantasia / Aventura', capa=''),
       Livro(nome='Jogos Vorazes', autor='Suzanne Collins', descricao='Competição mortal', genero='Distopia / Ficção Científica', capa=''),
        Livro( nome='A Hipótese do Amor', autor='Ali Hazelwood', descricao='Uma comédia romântica sobre cientistas fingindo um relacionamento', genero='Romance / Comédia',capa=''),
        Livro(nome='A Razão do Amor', autor='Ali Hazelwood', descricao='Uma engenheira e um físico enfrentam desafios profissionais e pessoais', genero='Romance / Comédia',capa=''),
        Livro(nome='Sob a Luz dos Seus Olhos', autor='Ali Hazelwood', descricao='Uma jovem cientista precisa lidar com o passado e o presente', genero='Romance / Drama',capa=''),
        Livro (nome='Amor, Teoria e Prática', autor='Ali Hazelwood', descricao='Uma história sobre mulheres na ciência e seus desafios amorosos', genero='Romance / Comédia',capa=''),
    ]

    for livro in livros:
        livro.data_inclusao = datetime.now(UTC)
        db.merge(livro)  # merge evita duplicação se ID já existir

    db.commit()
    db.close()
    print("Livros inseridos com sucesso.")

if __name__ == "__main__":
    inserir_livros_iniciais()
