# popular_livros.py

from sqlalchemy.orm import Session
from database import SessionLocal
from models import Livro
from datetime import datetime



def inserir_livros_iniciais():
    db: Session = SessionLocal()

    livros = [
        Livro(id=1, nome='O Senhor dos Anéis', autor='J.R.R. Tolkien', descricao='A Sociedade do Anel', genero='Fantasia'),
        Livro(id=2, nome='Harry Potter', autor='J.K. Rowling', descricao='A Pedra Filosofal', genero='Fantasia'),
        Livro(id=3, nome='Hábitos Atômicos', autor='James Clear', descricao='Guia prático para criar bons hábitos', genero='Desenvolvimento pessoal'),
        Livro(id=4, nome='1984', autor='George Orwell', descricao='Sociedade distópica sob vigilância', genero='Distopia'),
        Livro(id=5, nome='Dom Quixote', autor='Miguel de Cervantes', descricao='Cavaleiro em busca de justiça', genero='Clássico / Romance'),
        Livro(id=6, nome='O Pequeno Príncipe', autor='Antoine de Saint-Exupéry', descricao='Viagem filosófica e poética', genero='Fábula / Filosófico'),
        Livro(id=7, nome='A Revolução dos Bichos', autor='George Orwell', descricao='Sátira política com animais', genero='Sátira / Distopia'),
        Livro(id=8, nome='O Código Da Vinci', autor='Dan Brown', descricao='Suspense envolvendo religião e arte', genero='Suspense / Mistério'),
        Livro(id=9, nome='Moby Dick', autor='Herman Melville', descricao='A caça à baleia branca', genero='Aventura / Clássico'),
        Livro(id=10, nome='Crime e Castigo', autor='Fiódor Dostoiévski', descricao='Drama psicológico e culpa', genero='Drama psicológico / Clássico'),
        Livro(id=11, nome='O Alquimista', autor='Paulo Coelho', descricao='Jornada espiritual por um tesouro', genero='Ficção filosófica'),
        Livro(id=12, nome='A Guerra dos Tronos', autor='George R.R. Martin', descricao='Intrigas em Westeros', genero='Fantasia épica'),
        Livro(id=13, nome='O Morro dos Ventos Uivantes', autor='Emily Brontë', descricao='Romance gótico e vingança', genero='Romance gótico'),
        Livro(id=14, nome='Cem Anos de Solidão', autor='Gabriel García Márquez', descricao='Saga da família Buendía', genero='Realismo mágico'),
        Livro(id=15, nome='A Lâmina da Assassina', autor='Sarah J. Maas', descricao='Prelúdio da saga Trono de Vidro', genero='Fantasia / Jovem adulto'),
        Livro(id=16, nome='Trono de Vidro', autor='Sarah J. Maas', descricao='Assassina em competição mortal', genero='Fantasia / Jovem adulto'),
        Livro(id=17, nome='Coroa da Meia-Noite', autor='Sarah J. Maas', descricao='Segredos e traições', genero='Fantasia / Jovem adulto'),
        Livro(id=18, nome='Herdeira do Fogo', autor='Sarah J. Maas', descricao='Poderes despertando', genero='Fantasia / Jovem adulto'),
        Livro(id=19, nome='Rainha das Sombras', autor='Sarah J. Maas', descricao='Confronto com o passado', genero='Fantasia / Jovem adulto'),
        Livro(id=20, nome='Império de Tempestades', autor='Sarah J. Maas', descricao='Aliados improváveis', genero='Fantasia / Jovem adulto'),
        Livro(id=21, nome='Torre do Alvorecer', autor='Sarah J. Maas', descricao='Aventuras em novo continente', genero='Fantasia / Jovem adulto'),
        Livro(id=22, nome='Reino das Cinzas', autor='Sarah J. Maas', descricao='Conclusão épica', genero='Fantasia / Jovem adulto'),
        Livro(id=23, nome='Corte de Espinhos e Rosas', autor='Sarah J. Maas', descricao='Bela e a Fera reimaginado', genero='Fantasia / Romance / Jovem adulto'),
        Livro(id=24, nome='Corte de Névoa e Fúria', autor='Sarah J. Maas', descricao='Segredos do mundo feérico', genero='Fantasia / Romance / Jovem adulto'),
        Livro(id=25, nome='Corte de Asas e Ruína', autor='Sarah J. Maas', descricao='Batalha entre reinos', genero='Fantasia / Romance / Jovem adulto'),
        Livro(id=26, nome='Corte de Gelo e Estrelas', autor='Sarah J. Maas', descricao='História pós-guerra', genero='Fantasia / Romance / Jovem adulto'),
        Livro(id=27, nome='Corte de Chamas Prateadas', autor='Sarah J. Maas', descricao='Nova protagonista em ascensão', genero='Fantasia / Romance / New adult'),
        Livro(id=28, nome='Casa de Terra e Sangue', autor='Sarah J. Maas', descricao='Mundo urbano com magia', genero='Fantasia / New adult'),
        Livro(id=29, nome='Casa de Céu e Sopro', autor='Sarah J. Maas', descricao='Conflitos e revelações', genero='Fantasia / New adult'),
        Livro(id=30, nome='Casa de Chama e Sombra', autor='Sarah J. Maas', descricao='Último capítulo da saga', genero='Fantasia / New adult'),
        Livro(id=31, nome='Orgulho e Preconceito', autor='Jane Austen', descricao='Romance clássico sobre amor e sociedade', genero='Romance / Clássico'),
        Livro(id=32, nome='O Grande Gatsby', autor='F. Scott Fitzgerald', descricao='Crítica social e o sonho americano', genero='Clássico / Romance'),
        Livro(id=33, nome='As Crônicas de Nárnia: O Leão, a Feiticeira e o Guarda-Roupa', autor='C.S. Lewis', descricao='Aventuras em um mundo mágico', genero='Fantasia / Infantil'),
        Livro(id=34, nome='A Menina que Roubava Livros', autor='Markus Zusak', descricao='História emocionante ambientada na Segunda Guerra Mundial', genero='Drama Histórico'),
        Livro(id=35, nome='Percy Jackson e o Ladrão de Raios', autor='Rick Riordan', descricao='Um jovem descobre ser filho de um deus grego', genero='Fantasia / Mitologia / Jovem adulto'),
        Livro(id=36, nome='O Diário de Anne Frank', autor='Anne Frank', descricao='Relato da vida de uma adolescente durante o Holocausto', genero='Biografia / História'),
        Livro(id=37, nome='Ensaio sobre a Cegueira', autor='José Saramago', descricao='Uma epidemia de cegueira branca atinge uma cidade', genero='Distopia / Ficção Filosófica'),
        Livro(id=38, nome='O Conto da Aia', autor='Margaret Atwood', descricao='Sociedade totalitária onde mulheres são propriedade', genero='Distopia / Ficção Científica'),
        Livro(id=39, nome='Extraordinário', autor='R.J. Palacio', descricao='A vida de um menino com deformidade facial', genero='Drama / Jovem adulto'),
        Livro(id=40, nome='Sapiens: Uma Breve História da Humanidade', autor='Yuval Noah Harari', descricao='Exploração da história da humanidade', genero='Não Ficção / História'),
        Livro(id=41, nome='Mulheres que Correm com os Lobos', autor='Clarissa Pinkola Estés', descricao='Mitos e histórias sobre o poder feminino', genero='Psicologia / Feminismo'),
        Livro(id=42, nome='Mindset: A Nova Psicologia do Sucesso', autor='Carol S. Dweck', descricao='A importância da mentalidade no sucesso', genero='Desenvolvimento Pessoal / Psicologia'),
        Livro(id=43, nome='O Poder do Hábito', autor='Charles Duhigg', descricao='Como os hábitos funcionam e como podemos mudá-los', genero='Não Ficção / Psicologia'),
        Livro(id=44, nome='A Culpa é das Estrelas', autor='John Green', descricao='Romance adolescente sobre amor e doença', genero='Romance / Jovem adulto'),
        Livro(id=45, nome='Uma Breve História do Tempo', autor='Stephen Hawking', descricao='Explicação de conceitos cosmológicos para leigos', genero='Não Ficção / Ciência'),
        Livro(id=46, nome='O Silmarillion', autor='J.R.R. Tolkien', descricao='História da criação e mitologia da Terra-média', genero='Fantasia / Mitologia'),
        Livro(id=47, nome='O Hobbit', autor='J.R.R. Tolkien',   descricao='Aventura de Bilbo Bolseiro em busca de um tesouro', genero='Fantasia / Aventura'),   
        Livro(id=48, nome='O Nome do Vento', autor='Patrick Rothfuss', descricao='A história de Kvothe, um jovem prodígio', genero='Fantasia / Aventura'),
        Livro(id=49, nome='A Bússola de Ouro', autor='Philip Pullman', descricao='Aventuras em um mundo paralelo', genero='Fantasia / Aventura'),
        Livro(id=50, nome='O Senhor dos Anéis: As Duas Torres', autor='J.R.R. Tolkien', descricao='Continuação da jornada da Sociedade do Anel', genero='Fantasia / Aventura'),
        Livro(id=51, nome='O Senhor dos Anéis: O Retorno do Rei', autor='J.R.R. Tolkien', descricao='Conclusão épica da saga do Anel', genero='Fantasia / Aventura'),
        Livro(id=52, nome='A Rainha Vermelha', autor='Victoria Aveyard', descricao='Um mundo dividido entre sangue vermelho e prateado', genero='Fantasia / Jovem adulto'),
        Livro(id=53, nome='A Seleção', autor='Kiera Cass', descricao='Uma competição para se tornar a futura rainha', genero='Romance / Jovem adulto'),
        Livro(id=54, nome='A Esperança', autor='Suzanne Collins', descricao='O desfecho da trilogia Jogos Vorazes', genero='Distopia / Ficção Científica'),
        Livro(id=55, nome='Jogos Vorazes', autor='Suzanne Collins', descricao='Uma competição mortal em um futuro distópico', genero='Distopia / Ficção Científica'),
        Livro(id=56, nome='Em Chamas', autor='Suzanne Collins', descricao ='Continuação da luta de Katniss Everdeen', genero='Distopia / Ficção Científica'),
        Livro(id=57, nome='O Ódio que Você Semeia', autor='Angie Thomas', descricao='A luta contra o racismo e a brutalidade policial', genero='Drama / Jovem adulto'), 
        Livro(id=58, nome='O Sol é Para Todos', autor='Harper Lee', descricao='Uma história sobre justiça e moralidade no sul dos EUA', genero='Drama / Clássico'),
        Livro(id=59, nome='O Morro dos Ventos Uivantes', autor='Emily Brontë', descricao='Um romance gótico sobre amor e vingança', genero='Romance / Gótico'),
        Livro(id=60, nome='O Retrato de Dorian Gray', autor='Oscar Wilde', descricao='A busca pela beleza e juventude eterna', genero='Ficção / Clássico'),
        Livro(id=61, nome='O Processo', autor='Franz Kafka', descricao='Um homem é preso sem saber o motivo', genero='Ficção / Clássico'),
        Livro(id=62, nome='A Metamorfose', autor='Franz Kafka', descricao='Um homem se transforma em inseto', genero='Ficção / Clássico'),
        Livro(id=63, nome='O Apanhador no Campo de Centeio', autor='J.D. Salinger', descricao='A história de Holden Caulfield', genero='Romance / Clássico'),
        Livro(id=64, nome='O Sol Também é uma Estrela', autor='Nicola Yoon', descricao='Uma história de amor em um dia', genero='Romance / Jovem adulto'),
        Livro(id=65, nome='A Garota no Trem', autor='Paula Hawkins', descricao='Um thriller psicológico cheio de reviravoltas', genero='Thriller / Mistério'),
        Livro(id=66, nome='A Menina que Tinha Dons', autor='M.R. Carey', descricao='Uma história pós-apocalíptica com zumbis', genero='Ficção Científica / Terror'),
        Livro(id=67, nome='O Último Desejo', autor='Andrzej Sapkowski', descricao='As aventuras do bruxo Geralt de Rívia', genero='Fantasia / Aventura'),
        Livro(id=68, nome='A Canção do Sangue e Cinzas', autor='Rebecca Roanhorse', descricao='Uma fantasia inspirada na mitologia indígena americana', genero='Fantasia / Aventura'),
        Livro(id=69, nome='O Ciclo da Herança: Eragon', autor='Christopher Paolini', descricao='A jornada de um jovem dragão e seu cavaleiro', genero='Fantasia / Aventura'),
        Livro(id=70, nome='O Ciclo da Herança: Eldest', autor='Christopher Paolini', descricao ='Continuação da saga de Eragon e Saphira', genero ='Fantasia / Aventura'),
        Livro(id=71, nome ='O Ciclo da Herança: Brisingr' , autor ='Christopher Paolini' , descricao ='Eragon enfrenta novos desafios e inimigos' , genero ='Fantasia / Aventura'),
        Livro(id=72, nome ='O Ciclo da Herança: Herança' , autor ='Christopher Paolini' , descricao ='Conclusão da saga de Eragon e Saphira' , genero ='Fantasia / Aventura'),
        Livro(id=73, nome='A Rainha do Tearling', autor='Erika Johansen', descricao='Uma jovem rainha luta para recuperar seu trono', genero='Fantasia / Aventura'),
        Livro(id=74, nome='A Filha do Sangue', autor='Anne Bishop', descricao='Uma fantasia sombria sobre poder e magia', genero='Fantasia / Aventura'),
        Livro(id=75, nome='A Corte de Espinhos e Rosas', autor='Sarah J. Maas', descricao='Uma história de amor e vingança em um mundo feérico', genero='Fantasia / Romance / Jovem adulto'),
        Livro(id=76, nome='A Corte de Névoa e Fúria', autor='Sarah J. Maas', descricao='Segredos e traições em um mundo mágico', genero='Fantasia / Romance / Jovem adulto'),
        Livro(id=77, nome='A Corte de Asas e Ruína', autor='Sarah J. Maas', descricao='Batalha entre reinos e amor verdadeiro', genero='Fantasia / Romance / Jovem adulto'),
        Livro(id=78, nome='A Corte de Gelo e Estrelas', autor='Sarah J. Maas', descricao='História pós-guerra e novos desafios', genero='Fantasia / Romance / Jovem adulto'),
        Livro(id=79, nome='A Corte de Chamas Prateadas', autor='Sarah J. Maas', descricao='Nova protagonista em ascensão', genero='Fantasia / Romance / New adult'),
        Livro(id=80, nome='A Casa de Terra e Sangue', autor='Sarah J. Maas', descricao='Mundo urbano com magia e mistério', genero='Fantasia / New adult'),
        Livro(id=81, nome='A Casa de Céu e Sopro', autor='Sarah J. Maas', descricao='Conflitos e revelações em um mundo mágico', genero='Fantasia / New adult'),
        Livro(id=82, nome='A Casa de Chama e Sombra', autor='Sarah J. Maas', descricao='Último capítulo da saga com novos desafios', genero='Fantasia / New adult'),
        Livro(id=83, nome='O Nome do Vento', autor='Patrick Rothfuss', descricao='A história de Kvothe, um jovem prodígio', genero='Fantasia / Aventura'),
        Livro(id=84, nome='O Temor do Sábio', autor='Patrick Rothfuss', descricao='Continuação da jornada de Kvothe', genero='Fantasia / Aventura'),
        Livro(id=85, nome='A Música do Silêncio', autor='Patrick Rothfuss', descricao='Uma história paralela ao universo de Kvothe', genero='Fantasia / Aventura'),
        Livro(id=86, nome='O Príncipe Cruel', autor='Holly Black', descricao='Uma jovem mortal em um mundo feérico traiçoeiro', genero='Fantasia / Jovem adulto'),
        Livro(id=87, nome='A Rainha do Nada', autor='Holly Black', descricao='Conflitos e alianças em um mundo mágico', genero='Fantasia / Jovem adulto'),
        Livro(id=88, nome='A Maldição do Vencedor', autor='Marie Rutkoski', descricao='Uma história de amor e política em um mundo opressivo', genero='Fantasia / Jovem adulto'),
        Livro(id=89, nome='A Trança', autor='Laetitia Colombani', descricao='A história de três mulheres de diferentes culturas', genero='Drama / Ficção'),
        Livro(id=90, nome='O Castelo', autor='Franz Kafka', descricao='Um homem tenta acessar um castelo misterioso', genero='Ficção / Clássico'),
        Livro(id=91, nome='O Médico e o Monstro', autor='Robert Louis Stevenson', descricao='Dualidade do bem e do mal em um homem', genero='Terror / Clássico'),
        Livro(id=92, nome='O Velho e o Mar', autor='Ernest Hemingway', descricao='A luta de um velho pescador com um peixe gigante', genero='Ficção / Clássico'),
        Livro(id=93, nome='O Pequeno Nicolau', autor='René Goscinny', descricao='As aventuras de um menino travesso', genero='Infantil / Humor'),
        Livro(id=94, nome='O Pássaro Pintado', autor='Jerzy Kosinski', descricao='Sobrevivência de um menino na Segunda Guerra', genero='Drama / Guerra'),
        Livro(id=95, nome='O Homem Invisível', autor='H.G. Wells', descricao='Um cientista descobre como se tornar invisível', genero='Ficção Científica / Clássico'),
        Livro(id=96, nome='O Lobo da Estepe', autor='Hermann Hesse', descricao='Conflito existencial de um homem solitário', genero='Ficção / Filosófico'),
        Livro(id=97, nome='O Jogador', autor='Fiódor Dostoiévski', descricao='A obsessão pelo jogo e suas consequências', genero='Drama / Clássico'),
        Livro(id=98, nome='O Estrangeiro', autor='Albert Camus', descricao='A indiferença de um homem diante da vida', genero='Filosófico / Clássico'),
        Livro(id=99, nome='O Leopardo', autor='Giuseppe Tomasi di Lampedusa', descricao='Mudanças sociais na Sicília', genero='Romance / Histórico'),
        Livro(id=100, nome='O Homem Duplicado', autor='José Saramago', descricao='Um homem descobre seu sósia', genero='Ficção / Filosófico'),
        Livro(id=101, nome='O Físico', autor='Noah Gordon', descricao='A jornada de um jovem para se tornar médico', genero='Romance / Histórico'),
        Livro(id=102, nome='O Pintassilgo', autor='Donna Tartt', descricao='A vida de um jovem após uma tragédia', genero='Drama / Contemporâneo'),
        Livro(id=103, nome='O Pintor de Batalhas', autor='Arturo Pérez-Reverte', descricao='Reflexões de um fotógrafo de guerra', genero='Drama / Guerra'),
        Livro(id=104, nome='O Perfume', autor='Patrick Süskind', descricao='Um homem obcecado por criar o perfume perfeito', genero='Ficção / Suspense'),
        Livro(id=105, nome='O Pêndulo de Foucault', autor='Umberto Eco', descricao='Conspirações e sociedades secretas', genero='Ficção / Mistério'),
        Livro(id=106, nome='O Planeta dos Macacos', autor='Pierre Boulle', descricao='Humanos em um mundo dominado por macacos', genero='Ficção Científica / Distopia'),
        Livro(id=107, nome='O Primo Basílio', autor='José Maria de Eça de Queirós', descricao='Adultério na sociedade lisboeta', genero='Romance / Clássico'),
        Livro(id=108, nome='O Quinze', autor='Rachel de Queiroz', descricao='A seca no Nordeste brasileiro', genero='Romance / Regionalista'),
        Livro(id=109, nome='O Retrato', autor='Nikolai Gógol', descricao='Um retrato misterioso muda a vida de um homem', genero='Ficção / Fantástico'),
        Livro(id=110, nome='O Segredo do Meu Marido', autor='Liane Moriarty', descricao='Um segredo pode mudar tudo', genero='Romance / Suspense'),
        Livro(id=111, nome='O Senhor das Moscas', autor='William Golding', descricao='Meninos isolados em uma ilha', genero='Ficção / Distopia'),
        Livro(id=112, nome='O Sobrinho do Mago', autor='C.S. Lewis', descricao='A origem de Nárnia', genero='Fantasia / Infantil'),
        Livro(id=113, nome='O Sol é Para Todos', autor='Harper Lee', descricao='Justiça e racismo no sul dos EUA', genero='Drama / Clássico'),
        Livro(id=114, nome='O Som e a Fúria', autor='William Faulkner', descricao='A decadência de uma família sulista', genero='Ficção / Clássico'),
        Livro(id=115, nome='O Tempo e o Vento', autor='Erico Verissimo', descricao='Saga de uma família gaúcha', genero='Romance / Histórico'),
        Livro(id=116, nome='O Vermelho e o Negro', autor='Stendhal', descricao='Ambição e paixão na França pós-napoleônica', genero='Romance / Clássico'),
        Livro(id=117, nome='O Vendedor de Sonhos', autor='Augusto Cury', descricao='Um homem misterioso transforma vidas', genero='Ficção / Autoajuda'),
        Livro(id=118, nome='O Vilarejo', autor='Raphael Montes', descricao='Contos de terror em um vilarejo sombrio', genero='Terror / Suspense'),
        Livro(id=119, nome='Os Irmãos Karamázov', autor='Fiódor Dostoiévski', descricao='Conflitos familiares e existenciais', genero='Filosófico / Clássico'),
        Livro(id=120, nome='Os Maias', autor='José Maria de Eça de Queirós', descricao='Saga de uma família portuguesa', genero='Romance / Clássico'),
        Livro(id=121, nome='Os Miseráveis', autor='Victor Hugo', descricao='Luta pela justiça na França do século XIX', genero='Romance / Clássico'),
        Livro(id=122, nome='Os Pilares da Terra', autor='Ken Follett', descricao='Construção de uma catedral medieval', genero='Romance / Histórico'),
        Livro(id=123, nome='Os Sete Maridos de Evelyn Hugo', autor='Taylor Jenkins Reid', descricao='A vida de uma estrela de Hollywood', genero='Romance / Contemporâneo'),
        Livro(id=124, nome='Os Três Mosqueteiros', autor='Alexandre Dumas', descricao='Aventuras de d’Artagnan e seus amigos', genero='Aventura / Clássico'),
        Livro(id=125, nome='Outlander', autor='Diana Gabaldon', descricao='Uma mulher viaja no tempo para a Escócia do século XVIII', genero='Romance / Fantasia'),
        Livro(id=126, nome='Pai Rico, Pai Pobre', autor='Robert Kiyosaki', descricao='Lições sobre dinheiro e investimentos', genero='Finanças / Autoajuda'),
        Livro(id=127, nome='Pequenas Grandes Mentiras', autor='Liane Moriarty', descricao='Segredos e mentiras em uma comunidade', genero='Romance / Suspense'),
        Livro(id=128, nome='Peter Pan', autor='J.M. Barrie', descricao='O menino que não queria crescer', genero='Fantasia / Infantil'),
        Livro(id=129, nome='Pollyanna', autor='Eleanor H. Porter', descricao='O poder do otimismo', genero='Infantil / Clássico'),
        Livro(id=130, nome='Por Lugares Incríveis', autor='Jennifer Niven', descricao='Dois jovens lidam com traumas e descobertas', genero='Romance / Jovem adulto'),
        Livro(id=131, nome='Por Quem os Sinos Dobram', autor='Ernest Hemingway', descricao='A guerra civil espanhola', genero='Ficção / Guerra'),
        Livro(id=132, nome='Quarto de Despejo', autor='Carolina Maria de Jesus', descricao='O cotidiano na favela', genero='Biografia / Social'),
        Livro(id=133, nome='Quase Memória', autor='Carlos Heitor Cony', descricao='Recordações e ficção se misturam', genero='Romance / Brasileiro'),
        Livro(id=134, nome='Quincas Borba', autor='Machado de Assis', descricao='A filosofia do Humanitismo', genero='Romance / Clássico'),
        Livro(id=135, nome='Querido John', autor='Nicholas Sparks', descricao='Um amor à distância', genero='Romance / Drama'),
        Livro(id=136, nome='Rainha Vermelha', autor='Victoria Aveyard', descricao='Uma sociedade dividida por sangue', genero='Fantasia / Jovem adulto'),
        Livro(id=137, nome='Razão e Sensibilidade', autor='Jane Austen', descricao='Duas irmãs com personalidades opostas', genero='Romance / Clássico'),
        Livro(id=138, nome='Rebeca', autor='Daphne du Maurier', descricao='Mistério em uma mansão inglesa', genero='Suspense / Romance'),
        Livro(id=139, nome='Reinações de Narizinho', autor='Monteiro Lobato', descricao='Aventuras no Sítio do Picapau Amarelo', genero='Infantil / Fantasia'),
        Livro(id=140, nome='Ressurreição', autor='Machado de Assis', descricao='O amor e suas incertezas', genero='Romance / Clássico'),
        Livro(id=141, nome='Revolução dos Bichos', autor='George Orwell', descricao='Sátira política com animais', genero='Distopia / Sátira'),
        Livro(id=142, nome='Romeu e Julieta', autor='William Shakespeare', descricao='O amor proibido de dois jovens', genero='Tragédia / Clássico'),
        Livro(id=143, nome='Sagarana', autor='Guimarães Rosa', descricao='Contos do sertão brasileiro', genero='Regionalista / Contos'),
        Livro(id=144, nome='Salem', autor='Stephen King', descricao='Vampiros em uma pequena cidade', genero='Terror / Suspense'),
        Livro(id=145, nome='Senhora', autor='José de Alencar', descricao='Romance de interesse e redenção', genero='Romance / Clássico'),
        Livro(id=146, nome='Senhor dos Anéis: O Retorno do Rei', autor='J.R.R. Tolkien', descricao='Conclusão épica da saga', genero='Fantasia / Aventura'),
        Livro(id=147, nome='Seus Olhos', autor='Pedro Bandeira', descricao='Mistério juvenil brasileiro', genero='Juvenil / Mistério'),
        Livro(id=148, nome='Siddhartha', autor='Hermann Hesse', descricao='A busca espiritual de um jovem', genero='Filosófico / Clássico'),
        Livro(id=149, nome='Sobre a Escrita', autor='Stephen King', descricao='Memórias e dicas do mestre do terror', genero='Não Ficção / Escrita'),
        Livro(id=150, nome='Sociedade dos Poetas Mortos', autor='N.H. Kleinbaum', descricao='Inspiração e rebeldia em um colégio', genero='Drama / Jovem adulto'),
        Livro(id=151, nome='Solaris', autor='Stanisław Lem', descricao='Contato com uma inteligência alienígena', genero='Ficção Científica / Filosófico'),
        Livro(id=152, nome='Sonho de uma Noite de Verão', autor='William Shakespeare', descricao='Confusões amorosas e magia', genero='Comédia / Clássico'),
        Livro(id=153, nome='Stardust: O Mistério da Estrela', autor='Neil Gaiman', descricao='Uma aventura mágica por um reino encantado', genero='Fantasia / Aventura'),
        Livro(id=154, nome='Suicidas', autor='Raphael Montes', descricao='Mistério sobre um grupo de jovens', genero='Suspense / Policial'),
        Livro(id=155, nome='Tartarugas Até Lá Embaixo', autor='John Green', descricao='Uma jovem enfrenta o transtorno obsessivo-compulsivo', genero='Romance / Jovem adulto'),
        Livro(id=156, nome='Terra Sonâmbula', autor='Mia Couto', descricao='Dois viajantes em Moçambique devastado pela guerra', genero='Ficção / Africana'),
        Livro(id=157, nome='Toda Luz que Não Podemos Ver', autor='Anthony Doerr', descricao='Duas vidas durante a Segunda Guerra Mundial', genero='Drama / Histórico'),
        Livro(id=158, nome='Torto Arado', autor='Itamar Vieira Junior', descricao='A saga de duas irmãs no sertão baiano', genero='Romance / Brasileiro'),
        Livro(id=159, nome='Travessuras da Menina Má', autor='Mario Vargas Llosa', descricao='Um amor turbulento ao longo de décadas', genero='Romance / Contemporâneo'),
        Livro(id=160, nome='Trilogia da Fundação', autor='Isaac Asimov', descricao='O futuro da galáxia em jogo', genero='Ficção Científica / Clássico'),
        Livro(id=161, nome='Triste Fim de Policarpo Quaresma', autor='Lima Barreto', descricao='O nacionalismo exagerado de um funcionário público', genero='Romance / Brasileiro'),
        Livro(id=162, nome='Ulisses', autor='James Joyce', descricao='Um dia na vida de Leopold Bloom', genero='Ficção / Modernista'),
        Livro(id=163, nome='Um Conto de Duas Cidades', autor='Charles Dickens', descricao='A Revolução Francesa e seus impactos', genero='Romance / Histórico'),
        Livro(id=164, nome='Um Estudo em Vermelho', autor='Arthur Conan Doyle', descricao='Primeira aventura de Sherlock Holmes', genero='Mistério / Policial'),
        Livro(id=165, nome='Um Teto Todo Seu', autor='Virginia Woolf', descricao='A importância do espaço para a mulher escritora', genero='Ensaio / Feminismo'),
        Livro(id=166, nome='Vidas Secas', autor='Graciliano Ramos', descricao='A luta de uma família sertaneja', genero='Romance / Brasileiro'),
        Livro(id=167, nome='Vinte Mil Léguas Submarinas', autor='Júlio Verne', descricao='Aventuras do Capitão Nemo', genero='Ficção Científica / Aventura'),
        Livro(id=168, nome='Viúva de Ferro', autor='Xiran Jay Zhao', descricao='Uma jovem desafia o sistema em um mundo futurista', genero='Ficção Científica / Jovem adulto'),
        Livro(id=169, nome='Volta ao Mundo em 80 Dias', autor='Júlio Verne', descricao='Uma aposta leva a uma viagem extraordinária', genero='Aventura / Clássico'),
        Livro(id=170, nome='Vozes de Chernobyl', autor='Svetlana Alexievich', descricao='Relatos do desastre nuclear', genero='Não Ficção / História'),
        Livro(id=171, nome='O Orfanato da Srta. Peregrine para Crianças Peculiares', autor='Ransom Riggs', descricao='Crianças com habilidades especiais', genero='Fantasia / Jovem adulto'),
        Livro(id=172, nome='A Biblioteca da Meia-Noite', autor='Matt Haig', descricao='Entre a vida e a morte, uma biblioteca de escolhas', genero='Ficção / Fantasia'),
        Livro(id=173, nome='A Paciente Silenciosa', autor='Alex Michaelides', descricao='Uma mulher que para de falar após um crime', genero='Suspense / Thriller'),
        Livro(id=174, nome='A Vida Invisível de Addie LaRue', autor='V.E. Schwab', descricao='Uma jovem faz um pacto para viver para sempre', genero='Fantasia / Romance'),
        Livro(id=175, nome='A Troca', autor='Beth O’Leary', descricao='Duas mulheres trocam de vida por um tempo', genero='Romance / Comédia'),
        Livro(id=176, nome='A Última Festa', autor='Lucy Foley', descricao='Um assassinato em uma festa de Ano Novo', genero='Suspense / Mistério'),
        Livro(id=177, nome='A Última Carta de Amor', autor='Jojo Moyes', descricao='Cartas de amor perdidas no tempo', genero='Romance / Drama'),
        Livro(id=178, nome='A Vida Secreta das Abelhas', autor='Sue Monk Kidd', descricao='Uma jovem busca respostas sobre sua mãe', genero='Ficção / Drama'),
        Livro(id=179, nome='A Mulher na Janela', autor='A.J. Finn', descricao='Uma mulher testemunha algo suspeito pela janela', genero='Suspense / Thriller'),
        Livro(id=180, nome='A Mulher do Viajante no Tempo', autor='Audrey Niffenegger', descricao='Um amor afetado por viagens no tempo', genero='Romance / Fantasia'),
        Livro(id=181, nome='A Sombra do Vento', autor='Carlos Ruiz Zafón', descricao='Mistério em torno de um livro proibido', genero='Ficção / Mistério'),
        Livro(id=182, nome='A Garota Exemplar', autor='Gillian Flynn', descricao='O desaparecimento de uma mulher', genero='Suspense / Thriller'),
        Livro(id=183, nome='A Menina Submersa', autor='Caitlín R. Kiernan', descricao='Uma jovem lida com sua saúde mental', genero='Ficção / Fantasia Sombria'),
        Livro(id=184, nome='A Casa das Sete Mulheres', autor='Letícia Wierzchowski', descricao='Mulheres durante a Revolução Farroupilha', genero='Romance / Histórico'),
        Livro(id=185, nome='A Casa dos Espíritos', autor='Isabel Allende', descricao='Saga de uma família chilena', genero='Realismo Mágico / Romance'),
        Livro(id=186, nome='A Dança da Morte', autor='Stephen King', descricao='Uma epidemia apocalíptica', genero='Terror / Ficção Científica'),
        Livro(id=187, nome='A Elegância do Ouriço', autor='Muriel Barbery', descricao='A vida de uma porteira e uma menina prodígio', genero='Ficção / Contemporâneo'),
        Livro(id=188, nome='A Filha Perdida', autor='Elena Ferrante', descricao='Reflexões sobre maternidade', genero='Ficção / Drama'),
        Livro(id=189, nome='A Guardiã de Histórias', autor='Victoria Schwab', descricao='Uma jovem que pode ver fantasmas', genero='Fantasia / Jovem adulto'),
        Livro(id=190, nome='A Ilha do Tesouro', autor='Robert Louis Stevenson', descricao='Caça ao tesouro em alto-mar', genero='Aventura / Clássico'),
        Livro(id=191, nome='A Longa Viagem a um Pequeno Planeta Hostil', autor='Becky Chambers', descricao='Tripulação viaja pelo espaço', genero='Ficção Científica / Espaço'),
        Livro(id=192, nome='A Máquina do Tempo', autor='H.G. Wells', descricao='Viagem ao futuro distante', genero='Ficção Científica / Clássico'),
        Livro(id=193, nome='A Noiva Fantasma', autor='Yangsze Choo', descricao='Mistérios sobrenaturais na Malásia', genero='Fantasia / Romance'),
        Livro(id=194, nome='A Outra Volta do Parafuso', autor='Henry James', descricao='Uma governanta e aparições misteriosas', genero='Terror / Suspense'),
        Livro(id=195, nome='A Pequena Sereia', autor='Hans Christian Andersen', descricao='O conto original da sereia', genero='Fantasia / Clássico'),
        Livro(id=196, nome='A Redoma de Vidro', autor='Sylvia Plath', descricao='A luta de uma jovem contra a depressão', genero='Ficção / Drama'),
        Livro(id=197, nome='A Revolta de Atlas', autor='Ayn Rand', descricao='Uma sociedade à beira do colapso', genero='Ficção / Filosófico'),
        Livro(id=198, nome='A Rosa do Povo', autor='Carlos Drummond de Andrade', descricao='Poesia sobre o Brasil e o mundo', genero='Poesia / Brasileiro'),
        Livro(id=199, nome='A Sutil Arte de Ligar o F*da-se', autor='Mark Manson', descricao='Reflexões sobre a vida moderna', genero='Autoajuda / Não Ficção'),
        Livro(id=200, nome='A Última Música', autor='Nicholas Sparks', descricao='Reconciliação entre pai e filha', genero='Romance / Drama'),
        Livro(id=201, nome='A Hipótese do Amor', autor='Ali Hazelwood', descricao='Uma comédia romântica sobre cientistas fingindo um relacionamento', genero='Romance / Comédia'),
        Livro(id=202, nome='A Razão do Amor', autor='Ali Hazelwood', descricao='Uma engenheira e um físico enfrentam desafios profissionais e pessoais', genero='Romance / Comédia'),
        Livro(id=203, nome='Sob a Luz dos Seus Olhos', autor='Ali Hazelwood', descricao='Uma jovem cientista precisa lidar com o passado e o presente', genero='Romance / Drama'),
        Livro(id=204, nome='Amor, Teoria e Prática', autor='Ali Hazelwood', descricao='Uma história sobre mulheres na ciência e seus desafios amorosos', genero='Romance / Comédia'),
    ]

    for livro in livros:
        livro.data_inclusao = datetime.utcnow()
        db.merge(livro)  # merge evita duplicação se ID já existir

    db.commit()
    db.close()
    print("✅ Livros inseridos com sucesso.")

if __name__ == "__main__":
    inserir_livros_iniciais()
